job-service:
  url: http://job:8082

company-service:
  url: http://company:8081

review-service:
  url: http://review:8083

server:
  port: 8083

spring:
  application:
    name: review-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://postgres:5432/reviewmsdb
    driver-class-name: org.postgresql.Driver
    username: alexis
    password: alexis
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://servicereg:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    endpoint: 9412
