# Default profile (common settings)

job-service:
  url: http://job:8082

company-service:
  url: http://company:8081

review-service:
  url: http://review:8083

server:
  port: 8081

spring:
  application:
    name: company-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    config:
    #    activate:
    #      on-profile: prod

  datasource:
    url: jdbc:postgresql://postgres:5432/companymsdb
    driverClassName: org.postgresql.Driver
    username: alexis
    password: alexis
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#  profiles:
#    active: prod

#EUREKA DISCOVERY SETUP
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka/

# ZIPKIN
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    endpoint: 9412


# RabbitMQ


# Development profile
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  application:
#    name: company-service
#  datasource:
#    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#
#welcome:
#  message: Welcome to Alexis
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"
#
## Production profile
#---
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  config:
##    activate:
##      on-profile: prod
#  application:
#    name: company-service
#  datasource:
#    url: jdbc:postgresql://postgres:5432/companymsdb
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: 1236Jesus
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#
#welcome:
#  message: Welcome to Alexis
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"
