spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alex1-ai/application-config/

#server:
#  port: 8080

#EUREKA DISCOVERY SETUP
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka/
